# Custom Language File for Launcher Customizer

[ejs.app]
title = "Eidolyth Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Fab0uu/BerryBlue-Launcher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/CvFxSu6NHa"

[ejs.settings]
sourceGithubLink = "https://github.com/Fab0uu/BerryBlue-Launcher"
supportLink = "https://github.com/Fab0uu/BerryBlue-Launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Eidolyth"
welcomeDescription = "Eidolyth vous propose une expérience moddé unique réunissant Cobblemon, Create, Applied Energistics 2 et Mekanism. Un monde technique, vivant et collaboratif — prêt à accueillir votre aventure."
welcomeDescCTA = "Connectez-vous pour commencer."
